[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA路由重定向 - 确保所有路由都指向index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API路由重定向（如果有的话）
[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 